# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.resize(310, 230)
        MainWindow.setMinimumSize(QtCore.QSize(310, 230))
        MainWindow.setMaximumSize(QtCore.QSize(310, 230))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("app.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QtCore.QSize(32, 32))
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 291, 171))
        self.widget.setObjectName("widget")
        self.led_switch = QtWidgets.QPushButton(self.widget)
        self.led_switch.setEnabled(False)
        self.led_switch.setGeometry(QtCore.QRect(230, 12, 51, 23))
        self.led_switch.setCheckable(True)
        self.led_switch.setChecked(True)
        self.led_switch.setAutoDefault(True)
        self.led_switch.setObjectName("led_switch")
        self.brightness_str = QtWidgets.QLabel(self.widget)
        self.brightness_str.setGeometry(QtCore.QRect(10, 12, 61, 21))
        self.brightness_str.setObjectName("brightness_str")
        self.brightness_dp = QtWidgets.QLabel(self.widget)
        self.brightness_dp.setGeometry(QtCore.QRect(210, 12, 21, 21))
        self.brightness_dp.setObjectName("brightness_dp")
        self.brightness_slider = QtWidgets.QSlider(self.widget)
        self.brightness_slider.setGeometry(QtCore.QRect(80, 13, 111, 21))
        self.brightness_slider.setMaximum(48)
        self.brightness_slider.setPageStep(8)
        self.brightness_slider.setOrientation(QtCore.Qt.Horizontal)
        self.brightness_slider.setObjectName("brightness_slider")
        self.effect01_pb = QtWidgets.QPushButton(self.widget)
        self.effect01_pb.setGeometry(QtCore.QRect(70, 132, 51, 31))
        self.effect01_pb.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.effect01_pb.setCheckable(False)
        self.effect01_pb.setAutoDefault(True)
        self.effect01_pb.setObjectName("effect01_pb")
        self.effect02_pb = QtWidgets.QPushButton(self.widget)
        self.effect02_pb.setGeometry(QtCore.QRect(150, 132, 51, 31))
        self.effect02_pb.setCheckable(False)
        self.effect02_pb.setAutoDefault(True)
        self.effect02_pb.setObjectName("effect02_pb")
        self.effect03_pb = QtWidgets.QPushButton(self.widget)
        self.effect03_pb.setGeometry(QtCore.QRect(230, 132, 51, 31))
        self.effect03_pb.setCheckable(False)
        self.effect03_pb.setAutoDefault(True)
        self.effect03_pb.setObjectName("effect03_pb")
        self.customize_display_pb = QtWidgets.QPushButton(self.widget)
        self.customize_display_pb.setGeometry(QtCore.QRect(70, 52, 151, 23))
        self.customize_display_pb.setAutoDefault(True)
        self.customize_display_pb.setObjectName("customize_display_pb")
        self.str_input = QtWidgets.QLineEdit(self.widget)
        self.str_input.setGeometry(QtCore.QRect(70, 92, 111, 21))
        self.str_input.setObjectName("str_input")
        self.str_color_pb = QtWidgets.QPushButton(self.widget)
        self.str_color_pb.setGeometry(QtCore.QRect(190, 92, 41, 23))
        self.str_color_pb.setAutoDefault(True)
        self.str_color_pb.setObjectName("str_color_pb")
        self.mode0_str = QtWidgets.QLabel(self.widget)
        self.mode0_str.setGeometry(QtCore.QRect(10, 55, 61, 16))
        self.mode0_str.setObjectName("mode0_str")
        self.mode1_str = QtWidgets.QLabel(self.widget)
        self.mode1_str.setGeometry(QtCore.QRect(10, 95, 61, 16))
        self.mode1_str.setObjectName("mode1_str")
        self.mode2_str = QtWidgets.QLabel(self.widget)
        self.mode2_str.setGeometry(QtCore.QRect(10, 140, 61, 16))
        self.mode2_str.setObjectName("mode2_str")
        self.str_send_pb = QtWidgets.QPushButton(self.widget)
        self.str_send_pb.setGeometry(QtCore.QRect(240, 92, 41, 23))
        self.str_send_pb.setAutoDefault(True)
        self.str_send_pb.setObjectName("str_send_pb")
        self.Light_pb = QtWidgets.QPushButton(self.widget)
        self.Light_pb.setGeometry(QtCore.QRect(230, 52, 51, 23))
        self.Light_pb.setAutoDefault(True)
        self.Light_pb.setObjectName("Light_pb")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 310, 23))
        self.menuBar.setObjectName("menuBar")
        self.menu_file = QtWidgets.QMenu(self.menuBar)
        self.menu_file.setObjectName("menu_file")
        self.menu_help = QtWidgets.QMenu(self.menuBar)
        self.menu_help.setObjectName("menu_help")
        MainWindow.setMenuBar(self.menuBar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionServer = QtWidgets.QAction(MainWindow)
        self.actionServer.setObjectName("actionServer")
        self.actionPowerOFF = QtWidgets.QAction(MainWindow)
        self.actionPowerOFF.setObjectName("actionPowerOFF")
        self.actionReboot = QtWidgets.QAction(MainWindow)
        self.actionReboot.setObjectName("actionReboot")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setWhatsThis("")
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.menu_file.addAction(self.actionServer)
        self.menu_file.addAction(self.actionReboot)
        self.menu_file.addAction(self.actionPowerOFF)
        self.menu_file.addAction(self.actionExit)
        self.menu_help.addAction(self.actionHelp)
        self.menu_help.addAction(self.actionAbout)
        self.menuBar.addAction(self.menu_file.menuAction())
        self.menuBar.addAction(self.menu_help.menuAction())

        self.retranslateUi(MainWindow)
        self.brightness_slider.valueChanged['int'].connect(self.brightness_dp.setNum)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LEDControlTool"))
        self.led_switch.setStatusTip(_translate("MainWindow", "ON/OFF switch."))
        self.led_switch.setText(_translate("MainWindow", "ON"))
        self.brightness_str.setText(_translate("MainWindow", "<html><head/><body><p>Brightness</p></body></html>"))
        self.brightness_dp.setText(_translate("MainWindow", "0"))
        self.brightness_slider.setStatusTip(_translate("MainWindow", "Change the brightness."))
        self.effect01_pb.setStatusTip(_translate("MainWindow", "Display with effect01."))
        self.effect01_pb.setText(_translate("MainWindow", "01"))
        self.effect02_pb.setStatusTip(_translate("MainWindow", "Display with effect02."))
        self.effect02_pb.setText(_translate("MainWindow", "02"))
        self.effect03_pb.setStatusTip(_translate("MainWindow", "Display with effect03."))
        self.effect03_pb.setText(_translate("MainWindow", "03"))
        self.customize_display_pb.setStatusTip(_translate("MainWindow", "Customize Display."))
        self.customize_display_pb.setText(_translate("MainWindow", "Customize Display"))
        self.str_input.setStatusTip(_translate("MainWindow", "Enter the string to display."))
        self.str_color_pb.setStatusTip(_translate("MainWindow", "Set the color for string."))
        self.str_color_pb.setText(_translate("MainWindow", "color"))
        self.mode0_str.setText(_translate("MainWindow", "Mode0"))
        self.mode1_str.setText(_translate("MainWindow", "Mode1"))
        self.mode2_str.setText(_translate("MainWindow", "Mode2"))
        self.str_send_pb.setStatusTip(_translate("MainWindow", "Send to display."))
        self.str_send_pb.setText(_translate("MainWindow", "send"))
        self.Light_pb.setText(_translate("MainWindow", "Light"))
        self.menu_file.setTitle(_translate("MainWindow", "File"))
        self.menu_help.setTitle(_translate("MainWindow", "Help"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setStatusTip(_translate("MainWindow", "Exit."))
        self.actionServer.setText(_translate("MainWindow", "Server Config.."))
        self.actionServer.setStatusTip(_translate("MainWindow", "Server Config."))
        self.actionPowerOFF.setText(_translate("MainWindow", "PowerOFF"))
        self.actionPowerOFF.setStatusTip(_translate("MainWindow", "Shutdown the Raspberry Pi."))
        self.actionReboot.setText(_translate("MainWindow", "System Reboot"))
        self.actionReboot.setStatusTip(_translate("MainWindow", "Reboot the Raspberry Pi."))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionHelp.setStatusTip(_translate("MainWindow", "Help."))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionAbout.setStatusTip(_translate("MainWindow", "About."))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setStatusTip(_translate("MainWindow", "Save the config."))

