# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mode0.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Mode0Dlg(object):
    def setupUi(self, Mode0Dlg):
        Mode0Dlg.setObjectName("Mode0Dlg")
        Mode0Dlg.setWindowModality(QtCore.Qt.WindowModal)
        Mode0Dlg.resize(420, 180)
        Mode0Dlg.setMinimumSize(QtCore.QSize(420, 180))
        Mode0Dlg.setMaximumSize(QtCore.QSize(420, 180))
        Mode0Dlg.setFocusPolicy(QtCore.Qt.StrongFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("app.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Mode0Dlg.setWindowIcon(icon)
        self.widget = QtWidgets.QWidget(Mode0Dlg)
        self.widget.setGeometry(QtCore.QRect(10, 10, 401, 101))
        self.widget.setObjectName("widget")
        self.pushButton_00 = QtWidgets.QPushButton(self.widget)
        self.pushButton_00.setGeometry(QtCore.QRect(0, 80, 20, 20))
        self.pushButton_00.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_00.setText("")
        self.pushButton_00.setCheckable(False)
        self.pushButton_00.setObjectName("pushButton_00")
        self.pushButton_01 = QtWidgets.QPushButton(self.widget)
        self.pushButton_01.setGeometry(QtCore.QRect(0, 60, 20, 20))
        self.pushButton_01.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_01.setText("")
        self.pushButton_01.setCheckable(False)
        self.pushButton_01.setObjectName("pushButton_01")
        self.pushButton_02 = QtWidgets.QPushButton(self.widget)
        self.pushButton_02.setGeometry(QtCore.QRect(0, 40, 20, 20))
        self.pushButton_02.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_02.setText("")
        self.pushButton_02.setCheckable(False)
        self.pushButton_02.setObjectName("pushButton_02")
        self.pushButton_03 = QtWidgets.QPushButton(self.widget)
        self.pushButton_03.setGeometry(QtCore.QRect(0, 20, 20, 20))
        self.pushButton_03.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_03.setText("")
        self.pushButton_03.setCheckable(False)
        self.pushButton_03.setObjectName("pushButton_03")
        self.pushButton_04 = QtWidgets.QPushButton(self.widget)
        self.pushButton_04.setGeometry(QtCore.QRect(0, 0, 20, 20))
        self.pushButton_04.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_04.setText("")
        self.pushButton_04.setCheckable(False)
        self.pushButton_04.setObjectName("pushButton_04")
        self.pushButton_05 = QtWidgets.QPushButton(self.widget)
        self.pushButton_05.setGeometry(QtCore.QRect(20, 0, 20, 20))
        self.pushButton_05.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_05.setText("")
        self.pushButton_05.setCheckable(False)
        self.pushButton_05.setObjectName("pushButton_05")
        self.pushButton_06 = QtWidgets.QPushButton(self.widget)
        self.pushButton_06.setGeometry(QtCore.QRect(20, 20, 20, 20))
        self.pushButton_06.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_06.setText("")
        self.pushButton_06.setCheckable(False)
        self.pushButton_06.setObjectName("pushButton_06")
        self.pushButton_07 = QtWidgets.QPushButton(self.widget)
        self.pushButton_07.setGeometry(QtCore.QRect(20, 40, 20, 20))
        self.pushButton_07.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_07.setText("")
        self.pushButton_07.setCheckable(False)
        self.pushButton_07.setObjectName("pushButton_07")
        self.pushButton_08 = QtWidgets.QPushButton(self.widget)
        self.pushButton_08.setGeometry(QtCore.QRect(20, 60, 20, 20))
        self.pushButton_08.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_08.setText("")
        self.pushButton_08.setCheckable(False)
        self.pushButton_08.setObjectName("pushButton_08")
        self.pushButton_09 = QtWidgets.QPushButton(self.widget)
        self.pushButton_09.setGeometry(QtCore.QRect(20, 80, 20, 20))
        self.pushButton_09.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_09.setText("")
        self.pushButton_09.setCheckable(False)
        self.pushButton_09.setObjectName("pushButton_09")
        self.pushButton_10 = QtWidgets.QPushButton(self.widget)
        self.pushButton_10.setGeometry(QtCore.QRect(40, 80, 20, 20))
        self.pushButton_10.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_10.setText("")
        self.pushButton_10.setCheckable(False)
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.widget)
        self.pushButton_11.setGeometry(QtCore.QRect(40, 60, 20, 20))
        self.pushButton_11.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_11.setText("")
        self.pushButton_11.setCheckable(False)
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.widget)
        self.pushButton_12.setGeometry(QtCore.QRect(40, 40, 20, 20))
        self.pushButton_12.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_12.setText("")
        self.pushButton_12.setCheckable(False)
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.widget)
        self.pushButton_13.setGeometry(QtCore.QRect(40, 20, 20, 20))
        self.pushButton_13.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_13.setText("")
        self.pushButton_13.setCheckable(False)
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.widget)
        self.pushButton_14.setGeometry(QtCore.QRect(40, 0, 20, 20))
        self.pushButton_14.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_14.setText("")
        self.pushButton_14.setCheckable(False)
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(self.widget)
        self.pushButton_15.setGeometry(QtCore.QRect(60, 0, 20, 20))
        self.pushButton_15.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_15.setText("")
        self.pushButton_15.setCheckable(False)
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.widget)
        self.pushButton_16.setGeometry(QtCore.QRect(60, 20, 20, 20))
        self.pushButton_16.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_16.setText("")
        self.pushButton_16.setCheckable(False)
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(self.widget)
        self.pushButton_17.setGeometry(QtCore.QRect(60, 40, 20, 20))
        self.pushButton_17.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_17.setText("")
        self.pushButton_17.setCheckable(False)
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(self.widget)
        self.pushButton_18.setGeometry(QtCore.QRect(60, 60, 20, 20))
        self.pushButton_18.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_18.setText("")
        self.pushButton_18.setCheckable(False)
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(self.widget)
        self.pushButton_19.setGeometry(QtCore.QRect(60, 80, 20, 20))
        self.pushButton_19.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_19.setText("")
        self.pushButton_19.setCheckable(False)
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = QtWidgets.QPushButton(self.widget)
        self.pushButton_20.setGeometry(QtCore.QRect(80, 80, 20, 20))
        self.pushButton_20.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_20.setText("")
        self.pushButton_20.setCheckable(False)
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_21 = QtWidgets.QPushButton(self.widget)
        self.pushButton_21.setGeometry(QtCore.QRect(80, 60, 20, 20))
        self.pushButton_21.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_21.setText("")
        self.pushButton_21.setCheckable(False)
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_22 = QtWidgets.QPushButton(self.widget)
        self.pushButton_22.setGeometry(QtCore.QRect(80, 40, 20, 20))
        self.pushButton_22.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_22.setText("")
        self.pushButton_22.setCheckable(False)
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_23 = QtWidgets.QPushButton(self.widget)
        self.pushButton_23.setGeometry(QtCore.QRect(80, 20, 20, 20))
        self.pushButton_23.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_23.setText("")
        self.pushButton_23.setCheckable(False)
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_24 = QtWidgets.QPushButton(self.widget)
        self.pushButton_24.setGeometry(QtCore.QRect(80, 0, 20, 20))
        self.pushButton_24.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_24.setText("")
        self.pushButton_24.setCheckable(False)
        self.pushButton_24.setObjectName("pushButton_24")
        self.pushButton_25 = QtWidgets.QPushButton(self.widget)
        self.pushButton_25.setGeometry(QtCore.QRect(100, 0, 20, 20))
        self.pushButton_25.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_25.setText("")
        self.pushButton_25.setCheckable(False)
        self.pushButton_25.setObjectName("pushButton_25")
        self.pushButton_26 = QtWidgets.QPushButton(self.widget)
        self.pushButton_26.setGeometry(QtCore.QRect(100, 20, 20, 20))
        self.pushButton_26.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_26.setText("")
        self.pushButton_26.setCheckable(False)
        self.pushButton_26.setObjectName("pushButton_26")
        self.pushButton_27 = QtWidgets.QPushButton(self.widget)
        self.pushButton_27.setGeometry(QtCore.QRect(100, 40, 20, 20))
        self.pushButton_27.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_27.setText("")
        self.pushButton_27.setCheckable(False)
        self.pushButton_27.setObjectName("pushButton_27")
        self.pushButton_28 = QtWidgets.QPushButton(self.widget)
        self.pushButton_28.setGeometry(QtCore.QRect(100, 60, 20, 20))
        self.pushButton_28.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_28.setText("")
        self.pushButton_28.setCheckable(False)
        self.pushButton_28.setObjectName("pushButton_28")
        self.pushButton_29 = QtWidgets.QPushButton(self.widget)
        self.pushButton_29.setGeometry(QtCore.QRect(100, 80, 20, 20))
        self.pushButton_29.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_29.setText("")
        self.pushButton_29.setCheckable(False)
        self.pushButton_29.setObjectName("pushButton_29")
        self.pushButton_30 = QtWidgets.QPushButton(self.widget)
        self.pushButton_30.setGeometry(QtCore.QRect(120, 80, 20, 20))
        self.pushButton_30.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_30.setText("")
        self.pushButton_30.setCheckable(False)
        self.pushButton_30.setObjectName("pushButton_30")
        self.pushButton_31 = QtWidgets.QPushButton(self.widget)
        self.pushButton_31.setGeometry(QtCore.QRect(120, 60, 20, 20))
        self.pushButton_31.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_31.setText("")
        self.pushButton_31.setCheckable(False)
        self.pushButton_31.setObjectName("pushButton_31")
        self.pushButton_32 = QtWidgets.QPushButton(self.widget)
        self.pushButton_32.setGeometry(QtCore.QRect(120, 40, 20, 20))
        self.pushButton_32.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_32.setText("")
        self.pushButton_32.setCheckable(False)
        self.pushButton_32.setObjectName("pushButton_32")
        self.pushButton_33 = QtWidgets.QPushButton(self.widget)
        self.pushButton_33.setGeometry(QtCore.QRect(120, 20, 20, 20))
        self.pushButton_33.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_33.setText("")
        self.pushButton_33.setCheckable(False)
        self.pushButton_33.setObjectName("pushButton_33")
        self.pushButton_34 = QtWidgets.QPushButton(self.widget)
        self.pushButton_34.setGeometry(QtCore.QRect(120, 0, 20, 20))
        self.pushButton_34.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_34.setText("")
        self.pushButton_34.setCheckable(False)
        self.pushButton_34.setObjectName("pushButton_34")
        self.pushButton_35 = QtWidgets.QPushButton(self.widget)
        self.pushButton_35.setGeometry(QtCore.QRect(140, 0, 20, 20))
        self.pushButton_35.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_35.setText("")
        self.pushButton_35.setCheckable(False)
        self.pushButton_35.setObjectName("pushButton_35")
        self.pushButton_36 = QtWidgets.QPushButton(self.widget)
        self.pushButton_36.setGeometry(QtCore.QRect(140, 20, 20, 20))
        self.pushButton_36.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_36.setText("")
        self.pushButton_36.setCheckable(False)
        self.pushButton_36.setObjectName("pushButton_36")
        self.pushButton_37 = QtWidgets.QPushButton(self.widget)
        self.pushButton_37.setGeometry(QtCore.QRect(140, 40, 20, 20))
        self.pushButton_37.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_37.setText("")
        self.pushButton_37.setCheckable(False)
        self.pushButton_37.setObjectName("pushButton_37")
        self.pushButton_38 = QtWidgets.QPushButton(self.widget)
        self.pushButton_38.setGeometry(QtCore.QRect(140, 60, 20, 20))
        self.pushButton_38.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_38.setText("")
        self.pushButton_38.setCheckable(False)
        self.pushButton_38.setObjectName("pushButton_38")
        self.pushButton_39 = QtWidgets.QPushButton(self.widget)
        self.pushButton_39.setGeometry(QtCore.QRect(140, 80, 20, 20))
        self.pushButton_39.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_39.setText("")
        self.pushButton_39.setCheckable(False)
        self.pushButton_39.setObjectName("pushButton_39")
        self.pushButton_40 = QtWidgets.QPushButton(self.widget)
        self.pushButton_40.setGeometry(QtCore.QRect(160, 80, 20, 20))
        self.pushButton_40.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_40.setText("")
        self.pushButton_40.setCheckable(False)
        self.pushButton_40.setObjectName("pushButton_40")
        self.pushButton_41 = QtWidgets.QPushButton(self.widget)
        self.pushButton_41.setGeometry(QtCore.QRect(160, 60, 20, 20))
        self.pushButton_41.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_41.setText("")
        self.pushButton_41.setCheckable(False)
        self.pushButton_41.setObjectName("pushButton_41")
        self.pushButton_42 = QtWidgets.QPushButton(self.widget)
        self.pushButton_42.setGeometry(QtCore.QRect(160, 40, 20, 20))
        self.pushButton_42.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_42.setText("")
        self.pushButton_42.setCheckable(False)
        self.pushButton_42.setObjectName("pushButton_42")
        self.pushButton_43 = QtWidgets.QPushButton(self.widget)
        self.pushButton_43.setGeometry(QtCore.QRect(160, 20, 20, 20))
        self.pushButton_43.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_43.setText("")
        self.pushButton_43.setCheckable(False)
        self.pushButton_43.setObjectName("pushButton_43")
        self.pushButton_44 = QtWidgets.QPushButton(self.widget)
        self.pushButton_44.setGeometry(QtCore.QRect(160, 0, 20, 20))
        self.pushButton_44.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_44.setText("")
        self.pushButton_44.setCheckable(False)
        self.pushButton_44.setObjectName("pushButton_44")
        self.pushButton_45 = QtWidgets.QPushButton(self.widget)
        self.pushButton_45.setGeometry(QtCore.QRect(180, 0, 20, 20))
        self.pushButton_45.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_45.setText("")
        self.pushButton_45.setCheckable(False)
        self.pushButton_45.setObjectName("pushButton_45")
        self.pushButton_46 = QtWidgets.QPushButton(self.widget)
        self.pushButton_46.setGeometry(QtCore.QRect(180, 20, 20, 20))
        self.pushButton_46.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_46.setText("")
        self.pushButton_46.setCheckable(False)
        self.pushButton_46.setObjectName("pushButton_46")
        self.pushButton_47 = QtWidgets.QPushButton(self.widget)
        self.pushButton_47.setGeometry(QtCore.QRect(180, 40, 20, 20))
        self.pushButton_47.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_47.setText("")
        self.pushButton_47.setCheckable(False)
        self.pushButton_47.setObjectName("pushButton_47")
        self.pushButton_48 = QtWidgets.QPushButton(self.widget)
        self.pushButton_48.setGeometry(QtCore.QRect(180, 60, 20, 20))
        self.pushButton_48.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_48.setText("")
        self.pushButton_48.setCheckable(False)
        self.pushButton_48.setObjectName("pushButton_48")
        self.pushButton_49 = QtWidgets.QPushButton(self.widget)
        self.pushButton_49.setGeometry(QtCore.QRect(180, 80, 20, 20))
        self.pushButton_49.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_49.setText("")
        self.pushButton_49.setCheckable(False)
        self.pushButton_49.setObjectName("pushButton_49")
        self.pushButton_50 = QtWidgets.QPushButton(self.widget)
        self.pushButton_50.setGeometry(QtCore.QRect(200, 80, 20, 20))
        self.pushButton_50.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_50.setText("")
        self.pushButton_50.setCheckable(False)
        self.pushButton_50.setObjectName("pushButton_50")
        self.pushButton_51 = QtWidgets.QPushButton(self.widget)
        self.pushButton_51.setGeometry(QtCore.QRect(200, 60, 20, 20))
        self.pushButton_51.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_51.setText("")
        self.pushButton_51.setCheckable(False)
        self.pushButton_51.setObjectName("pushButton_51")
        self.pushButton_52 = QtWidgets.QPushButton(self.widget)
        self.pushButton_52.setGeometry(QtCore.QRect(200, 40, 20, 20))
        self.pushButton_52.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_52.setText("")
        self.pushButton_52.setCheckable(False)
        self.pushButton_52.setObjectName("pushButton_52")
        self.pushButton_53 = QtWidgets.QPushButton(self.widget)
        self.pushButton_53.setGeometry(QtCore.QRect(200, 20, 20, 20))
        self.pushButton_53.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_53.setText("")
        self.pushButton_53.setCheckable(False)
        self.pushButton_53.setObjectName("pushButton_53")
        self.pushButton_54 = QtWidgets.QPushButton(self.widget)
        self.pushButton_54.setGeometry(QtCore.QRect(200, 0, 20, 20))
        self.pushButton_54.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_54.setText("")
        self.pushButton_54.setCheckable(False)
        self.pushButton_54.setObjectName("pushButton_54")
        self.pushButton_55 = QtWidgets.QPushButton(self.widget)
        self.pushButton_55.setGeometry(QtCore.QRect(220, 0, 20, 20))
        self.pushButton_55.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_55.setText("")
        self.pushButton_55.setCheckable(False)
        self.pushButton_55.setObjectName("pushButton_55")
        self.pushButton_56 = QtWidgets.QPushButton(self.widget)
        self.pushButton_56.setGeometry(QtCore.QRect(220, 20, 20, 20))
        self.pushButton_56.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_56.setText("")
        self.pushButton_56.setCheckable(False)
        self.pushButton_56.setObjectName("pushButton_56")
        self.pushButton_57 = QtWidgets.QPushButton(self.widget)
        self.pushButton_57.setGeometry(QtCore.QRect(220, 40, 20, 20))
        self.pushButton_57.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_57.setText("")
        self.pushButton_57.setCheckable(False)
        self.pushButton_57.setObjectName("pushButton_57")
        self.pushButton_58 = QtWidgets.QPushButton(self.widget)
        self.pushButton_58.setGeometry(QtCore.QRect(220, 60, 20, 20))
        self.pushButton_58.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_58.setText("")
        self.pushButton_58.setCheckable(False)
        self.pushButton_58.setObjectName("pushButton_58")
        self.pushButton_59 = QtWidgets.QPushButton(self.widget)
        self.pushButton_59.setGeometry(QtCore.QRect(220, 80, 20, 20))
        self.pushButton_59.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_59.setText("")
        self.pushButton_59.setCheckable(False)
        self.pushButton_59.setObjectName("pushButton_59")
        self.pushButton_60 = QtWidgets.QPushButton(self.widget)
        self.pushButton_60.setGeometry(QtCore.QRect(240, 80, 20, 20))
        self.pushButton_60.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_60.setText("")
        self.pushButton_60.setCheckable(False)
        self.pushButton_60.setObjectName("pushButton_60")
        self.pushButton_61 = QtWidgets.QPushButton(self.widget)
        self.pushButton_61.setGeometry(QtCore.QRect(240, 60, 20, 20))
        self.pushButton_61.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_61.setText("")
        self.pushButton_61.setCheckable(False)
        self.pushButton_61.setObjectName("pushButton_61")
        self.pushButton_62 = QtWidgets.QPushButton(self.widget)
        self.pushButton_62.setGeometry(QtCore.QRect(240, 40, 20, 20))
        self.pushButton_62.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_62.setText("")
        self.pushButton_62.setCheckable(False)
        self.pushButton_62.setObjectName("pushButton_62")
        self.pushButton_63 = QtWidgets.QPushButton(self.widget)
        self.pushButton_63.setGeometry(QtCore.QRect(240, 20, 20, 20))
        self.pushButton_63.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_63.setText("")
        self.pushButton_63.setCheckable(False)
        self.pushButton_63.setObjectName("pushButton_63")
        self.pushButton_64 = QtWidgets.QPushButton(self.widget)
        self.pushButton_64.setGeometry(QtCore.QRect(240, 0, 20, 20))
        self.pushButton_64.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_64.setText("")
        self.pushButton_64.setCheckable(False)
        self.pushButton_64.setObjectName("pushButton_64")
        self.pushButton_65 = QtWidgets.QPushButton(self.widget)
        self.pushButton_65.setGeometry(QtCore.QRect(260, 0, 20, 20))
        self.pushButton_65.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_65.setText("")
        self.pushButton_65.setCheckable(False)
        self.pushButton_65.setObjectName("pushButton_65")
        self.pushButton_66 = QtWidgets.QPushButton(self.widget)
        self.pushButton_66.setGeometry(QtCore.QRect(260, 20, 20, 20))
        self.pushButton_66.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_66.setText("")
        self.pushButton_66.setCheckable(False)
        self.pushButton_66.setObjectName("pushButton_66")
        self.pushButton_67 = QtWidgets.QPushButton(self.widget)
        self.pushButton_67.setGeometry(QtCore.QRect(260, 40, 20, 20))
        self.pushButton_67.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_67.setText("")
        self.pushButton_67.setCheckable(False)
        self.pushButton_67.setObjectName("pushButton_67")
        self.pushButton_68 = QtWidgets.QPushButton(self.widget)
        self.pushButton_68.setGeometry(QtCore.QRect(260, 60, 20, 20))
        self.pushButton_68.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_68.setText("")
        self.pushButton_68.setCheckable(False)
        self.pushButton_68.setObjectName("pushButton_68")
        self.pushButton_69 = QtWidgets.QPushButton(self.widget)
        self.pushButton_69.setGeometry(QtCore.QRect(260, 80, 20, 20))
        self.pushButton_69.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_69.setText("")
        self.pushButton_69.setCheckable(False)
        self.pushButton_69.setObjectName("pushButton_69")
        self.pushButton_70 = QtWidgets.QPushButton(self.widget)
        self.pushButton_70.setGeometry(QtCore.QRect(280, 80, 20, 20))
        self.pushButton_70.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_70.setText("")
        self.pushButton_70.setCheckable(False)
        self.pushButton_70.setObjectName("pushButton_70")
        self.pushButton_71 = QtWidgets.QPushButton(self.widget)
        self.pushButton_71.setGeometry(QtCore.QRect(280, 60, 20, 20))
        self.pushButton_71.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_71.setText("")
        self.pushButton_71.setCheckable(False)
        self.pushButton_71.setObjectName("pushButton_71")
        self.pushButton_72 = QtWidgets.QPushButton(self.widget)
        self.pushButton_72.setGeometry(QtCore.QRect(280, 40, 20, 20))
        self.pushButton_72.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_72.setText("")
        self.pushButton_72.setCheckable(False)
        self.pushButton_72.setObjectName("pushButton_72")
        self.pushButton_73 = QtWidgets.QPushButton(self.widget)
        self.pushButton_73.setGeometry(QtCore.QRect(280, 20, 20, 20))
        self.pushButton_73.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_73.setText("")
        self.pushButton_73.setCheckable(False)
        self.pushButton_73.setObjectName("pushButton_73")
        self.pushButton_74 = QtWidgets.QPushButton(self.widget)
        self.pushButton_74.setGeometry(QtCore.QRect(280, 0, 20, 20))
        self.pushButton_74.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_74.setText("")
        self.pushButton_74.setCheckable(False)
        self.pushButton_74.setObjectName("pushButton_74")
        self.pushButton_75 = QtWidgets.QPushButton(self.widget)
        self.pushButton_75.setGeometry(QtCore.QRect(300, 0, 20, 20))
        self.pushButton_75.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_75.setText("")
        self.pushButton_75.setCheckable(False)
        self.pushButton_75.setObjectName("pushButton_75")
        self.pushButton_76 = QtWidgets.QPushButton(self.widget)
        self.pushButton_76.setGeometry(QtCore.QRect(300, 20, 20, 20))
        self.pushButton_76.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_76.setText("")
        self.pushButton_76.setCheckable(False)
        self.pushButton_76.setObjectName("pushButton_76")
        self.pushButton_77 = QtWidgets.QPushButton(self.widget)
        self.pushButton_77.setGeometry(QtCore.QRect(300, 40, 20, 20))
        self.pushButton_77.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_77.setText("")
        self.pushButton_77.setCheckable(False)
        self.pushButton_77.setObjectName("pushButton_77")
        self.pushButton_78 = QtWidgets.QPushButton(self.widget)
        self.pushButton_78.setGeometry(QtCore.QRect(300, 60, 20, 20))
        self.pushButton_78.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_78.setText("")
        self.pushButton_78.setCheckable(False)
        self.pushButton_78.setObjectName("pushButton_78")
        self.pushButton_79 = QtWidgets.QPushButton(self.widget)
        self.pushButton_79.setGeometry(QtCore.QRect(300, 80, 20, 20))
        self.pushButton_79.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_79.setText("")
        self.pushButton_79.setCheckable(False)
        self.pushButton_79.setObjectName("pushButton_79")
        self.pushButton_80 = QtWidgets.QPushButton(self.widget)
        self.pushButton_80.setGeometry(QtCore.QRect(320, 80, 20, 20))
        self.pushButton_80.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_80.setText("")
        self.pushButton_80.setCheckable(False)
        self.pushButton_80.setObjectName("pushButton_80")
        self.pushButton_81 = QtWidgets.QPushButton(self.widget)
        self.pushButton_81.setGeometry(QtCore.QRect(320, 60, 20, 20))
        self.pushButton_81.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_81.setText("")
        self.pushButton_81.setCheckable(False)
        self.pushButton_81.setObjectName("pushButton_81")
        self.pushButton_82 = QtWidgets.QPushButton(self.widget)
        self.pushButton_82.setGeometry(QtCore.QRect(320, 40, 20, 20))
        self.pushButton_82.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_82.setText("")
        self.pushButton_82.setCheckable(False)
        self.pushButton_82.setObjectName("pushButton_82")
        self.pushButton_83 = QtWidgets.QPushButton(self.widget)
        self.pushButton_83.setGeometry(QtCore.QRect(320, 20, 20, 20))
        self.pushButton_83.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_83.setText("")
        self.pushButton_83.setCheckable(False)
        self.pushButton_83.setObjectName("pushButton_83")
        self.pushButton_84 = QtWidgets.QPushButton(self.widget)
        self.pushButton_84.setGeometry(QtCore.QRect(320, 0, 20, 20))
        self.pushButton_84.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_84.setText("")
        self.pushButton_84.setCheckable(False)
        self.pushButton_84.setObjectName("pushButton_84")
        self.pushButton_85 = QtWidgets.QPushButton(self.widget)
        self.pushButton_85.setGeometry(QtCore.QRect(340, 0, 20, 20))
        self.pushButton_85.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_85.setText("")
        self.pushButton_85.setCheckable(False)
        self.pushButton_85.setObjectName("pushButton_85")
        self.pushButton_86 = QtWidgets.QPushButton(self.widget)
        self.pushButton_86.setGeometry(QtCore.QRect(340, 20, 20, 20))
        self.pushButton_86.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_86.setText("")
        self.pushButton_86.setCheckable(False)
        self.pushButton_86.setObjectName("pushButton_86")
        self.pushButton_87 = QtWidgets.QPushButton(self.widget)
        self.pushButton_87.setGeometry(QtCore.QRect(340, 40, 20, 20))
        self.pushButton_87.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_87.setText("")
        self.pushButton_87.setCheckable(False)
        self.pushButton_87.setObjectName("pushButton_87")
        self.pushButton_88 = QtWidgets.QPushButton(self.widget)
        self.pushButton_88.setGeometry(QtCore.QRect(340, 60, 20, 20))
        self.pushButton_88.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_88.setText("")
        self.pushButton_88.setCheckable(False)
        self.pushButton_88.setObjectName("pushButton_88")
        self.pushButton_89 = QtWidgets.QPushButton(self.widget)
        self.pushButton_89.setGeometry(QtCore.QRect(340, 80, 20, 20))
        self.pushButton_89.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_89.setText("")
        self.pushButton_89.setCheckable(False)
        self.pushButton_89.setObjectName("pushButton_89")
        self.pushButton_90 = QtWidgets.QPushButton(self.widget)
        self.pushButton_90.setGeometry(QtCore.QRect(360, 80, 20, 20))
        self.pushButton_90.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_90.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton_90.setText("")
        self.pushButton_90.setCheckable(False)
        self.pushButton_90.setObjectName("pushButton_90")
        self.pushButton_91 = QtWidgets.QPushButton(self.widget)
        self.pushButton_91.setGeometry(QtCore.QRect(360, 60, 20, 20))
        self.pushButton_91.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_91.setText("")
        self.pushButton_91.setCheckable(False)
        self.pushButton_91.setObjectName("pushButton_91")
        self.pushButton_92 = QtWidgets.QPushButton(self.widget)
        self.pushButton_92.setGeometry(QtCore.QRect(360, 40, 20, 20))
        self.pushButton_92.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_92.setText("")
        self.pushButton_92.setCheckable(False)
        self.pushButton_92.setObjectName("pushButton_92")
        self.pushButton_93 = QtWidgets.QPushButton(self.widget)
        self.pushButton_93.setGeometry(QtCore.QRect(360, 20, 20, 20))
        self.pushButton_93.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_93.setText("")
        self.pushButton_93.setCheckable(False)
        self.pushButton_93.setObjectName("pushButton_93")
        self.pushButton_94 = QtWidgets.QPushButton(self.widget)
        self.pushButton_94.setGeometry(QtCore.QRect(360, 0, 20, 20))
        self.pushButton_94.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_94.setText("")
        self.pushButton_94.setCheckable(False)
        self.pushButton_94.setObjectName("pushButton_94")
        self.pushButton_95 = QtWidgets.QPushButton(self.widget)
        self.pushButton_95.setGeometry(QtCore.QRect(380, 0, 20, 20))
        self.pushButton_95.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_95.setText("")
        self.pushButton_95.setCheckable(False)
        self.pushButton_95.setObjectName("pushButton_95")
        self.pushButton_96 = QtWidgets.QPushButton(self.widget)
        self.pushButton_96.setGeometry(QtCore.QRect(380, 20, 20, 20))
        self.pushButton_96.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_96.setText("")
        self.pushButton_96.setCheckable(False)
        self.pushButton_96.setObjectName("pushButton_96")
        self.pushButton_97 = QtWidgets.QPushButton(self.widget)
        self.pushButton_97.setGeometry(QtCore.QRect(380, 40, 20, 20))
        self.pushButton_97.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_97.setText("")
        self.pushButton_97.setCheckable(False)
        self.pushButton_97.setObjectName("pushButton_97")
        self.pushButton_98 = QtWidgets.QPushButton(self.widget)
        self.pushButton_98.setGeometry(QtCore.QRect(380, 60, 20, 20))
        self.pushButton_98.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_98.setText("")
        self.pushButton_98.setCheckable(False)
        self.pushButton_98.setObjectName("pushButton_98")
        self.pushButton_99 = QtWidgets.QPushButton(self.widget)
        self.pushButton_99.setGeometry(QtCore.QRect(380, 80, 20, 20))
        self.pushButton_99.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_99.setText("")
        self.pushButton_99.setCheckable(False)
        self.pushButton_99.setObjectName("pushButton_99")
        self.pushButton_all = QtWidgets.QPushButton(Mode0Dlg)
        self.pushButton_all.setGeometry(QtCore.QRect(20, 130, 81, 31))
        self.pushButton_all.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton_all.setObjectName("pushButton_all")
        self.pushButton_clear = QtWidgets.QPushButton(Mode0Dlg)
        self.pushButton_clear.setGeometry(QtCore.QRect(220, 130, 81, 31))
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.pushButton_color = QtWidgets.QPushButton(Mode0Dlg)
        self.pushButton_color.setGeometry(QtCore.QRect(320, 130, 81, 31))
        self.pushButton_color.setObjectName("pushButton_color")
        self.pushButton_filling = QtWidgets.QPushButton(Mode0Dlg)
        self.pushButton_filling.setGeometry(QtCore.QRect(120, 130, 81, 31))
        self.pushButton_filling.setObjectName("pushButton_filling")

        self.retranslateUi(Mode0Dlg)
        QtCore.QMetaObject.connectSlotsByName(Mode0Dlg)

    def retranslateUi(self, Mode0Dlg):
        _translate = QtCore.QCoreApplication.translate
        Mode0Dlg.setWindowTitle(_translate("Mode0Dlg", "Customize Display"))
        self.pushButton_all.setText(_translate("Mode0Dlg", "Check All"))
        self.pushButton_clear.setText(_translate("Mode0Dlg", "Clear"))
        self.pushButton_color.setText(_translate("Mode0Dlg", "Color"))
        self.pushButton_filling.setText(_translate("Mode0Dlg", "Filling"))

